#!/usr/bin/env bash

function check() {
  if [ -e "/tmp/StartSystemCheck" ]; then
    exit 0
  else
    touch ~/.config/picom.conf
    echo -e "Type your password to run startup script\npress enter to continue..."
    if [ $? == 0 ]; then     
      read
      run
    fi
  fi
}

function run() {
  ~/.config/startup/run
  sleep 5
#  clear
}

function main() {
  check
}

main
